in0out1=["sql-instream","model-instream","data-instream",]
in1out0=["data-outstream","sql-outstream","model-outstream",]
in1out1=["random","sql-execute",]
in1out2=["split-col","split-row",]
in2out1=["adaboost","svm","neural-network","knn","naive-bayes","decision-tree","merge-row","merge-col","predict",]
in2out2=[]
