details = {
  "adaboost":[
    {
      "name":"method",
      "display":"方法",
      "type":"list",
      "default":"classify",
      "list":[
        "classify",
        "regress"
      ]
    },
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "svm":[
    {
      "name":"method",
      "display":"方法",
      "type":"list",
      "default":"classify",
      "list":[
        "classify",
        "regress"
      ]
    },
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "neural-network":[
    {
      "name":"method",
      "display":"方法",
      "type":"list",
      "default":"classify",
      "list":[
        "classify",
        "regress"
      ]
    },
    {
      "name":"activation",
      "display":"激发函数",
      "type":"list",
      "default":"relu",
      "list":[
        "relu",
        "identity",
        "logistic",
        "tanh"
      ]
    },
    {
      "name":"solver",
      "display":"优化器",
      "type":"list",
      "default":"adam",
      "list":[
        "adam",
        "lbfgs",
        "sgd"
      ]
    },
    {
      "name":"alpha",
      "display":"alpha",
      "type":"number",
      "default":"0.0001"
    },
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "knn":[
    {
      "name":"method",
      "display":"方法",
      "type":"list",
      "default":"classify",
      "list":[
        "classify",
        "regress"
      ]
    },
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "naive-bayes":[
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "decision-tree":[
    {
      "name":"method",
      "display":"方法",
      "type":"list",
      "default":"classify",
      "list":[
        "classify",
        "regress"
      ]
    },
    {
      "name":"label_columns",
      "display":"标签列",
      "type":"text",
      "default":"label"
    }
  ],
  "sql-instream":[
    {
      "name":"database-type",
      "display":"数据库类型",
      "type":"list",
      "default":"MySQL",
      "list":[
        "MySQL",
        "sqlite",
        "oracle",
        "SQLServer",
        "PostgreSQL"
      ]
    },
    {
      "name":"address",
      "display":"地址",
      "type":"text",
      "default":"localhost"
    },
    {
      "name":"port",
      "display":"端口",
      "type":"text",
      "default":"3306"
    },
    {
      "name":"user",
      "display":"账号",
      "type":"text",
      "default":"root"
    },
    {
      "name":"password",
      "display":"密码",
      "type":"password",
      "default":"123"
    },
    {
      "name":"database-name",
      "display":"数据库名",
      "type":"text",
      "default":""
    },
    {
      "name":"command",
      "display":"SQL查询语句",
      "type":"richtext",
      "default":"SELECT *\nFROM tableA"
    }
  ],
  "model-instream":[
    {
      "name":"path",
      "display":"文件名",
      "type":"text",
      "default":""
    }
  ],
  "data-outstream":[
    {
      "name":"path",
      "display":"文件名",
      "type":"text",
      "default":""
    }
  ],
  "data-instream":[
    {
      "name":"path",
      "display":"文件名",
      "type":"text",
      "default":""
    }
  ],
  "sql-outstream":[
    {
      "name":"database-type",
      "display":"数据库类型",
      "type":"list",
      "default":"MySQL",
      "list":[
        "MySQL",
        "sqlite",
        "oracle",
        "SQLServer",
        "PostgreSQL"
      ]
    },
    {
      "name":"address",
      "display":"地址",
      "type":"text",
      "default":"localhost"
    },
    {
      "name":"port",
      "display":"端口",
      "type":"text",
      "default":"3306"
    },
    {
      "name":"user",
      "display":"账号",
      "type":"text",
      "default":"root"
    },
    {
      "name":"password",
      "display":"密码",
      "type":"password",
      "default":"root"
    },
    {
      "name":"database-name",
      "display":"数据库名",
      "type":"text",
      "default":""
    },
    {
      "name":"table-name",
      "display":"表名",
      "type":"text",
      "default":""
    },
    {
      "name":"if_exists",
      "display":"冲突解决方式",
      "type":"list",
      "default":"fail",
      "list":[
        "replace",
        "append",
        "fail"
      ]
    }
  ],
  "model-outstream":[
    {
      "name":"path",
      "display":"文件名",
      "type":"text",
      "default":""
    }
  ],
  "sort":[
    {
      "name":"columns",
      "display":"列名",
      "type":"text",
      "default":""
    },
    {
      "name":"ascending",
      "display":"升序",
      "type":"list",
      "default":"True",
      "list":[
        "True",
        "False"
      ]
    },
    {
      "name":"na_position",
      "display":"Nan所在位置",
      "type":"list",
      "default":"last",
      "list":[
        "first",
        "last"
      ]
    }
  ],
  "random":[],
  "sql-execute":[
    {
      "name":"sql_command",
      "display":"SQL语句,用{this}指代该表",
      "type":"richtext",
      "default":"SELECT * \nFROM {this}"
    }
  ],
  "fillna":[
    {
      "name":"fill_type",
      "display":"填充方式",
      "type":"list",
      "default":"all",
      "list":[
        "all",
        "specific",
        "ffill"
      ]
    },
    {
      "name":"value",
      "display":"值(all,specific)",
      "type":"text",
      "default":"0"
    }
  ],
  "drop_duplicate":[
    {
      "name":"columns",
      "display":"过滤列名",
      "type":"text",
      "default":""
    },
    {
      "name":"keep",
      "display":"保留方式",
      "type":"list",
      "default":"first",
      "list":[
        "first",
        "last",
        "None"
      ]
    }
  ],
  "dropna":[
    {
      "name":"drop_type",
      "display":"类型",
      "type":"list",
      "default":"row",
      "list":[
        "row",
        "col",
        "all"
      ]
    }
  ],
  "predict":[],
  "split-col":[
    {
      "name":"columns",
      "display":"列名",
      "type":"text",
      "default":""
    }
  ],
  "split-row":[
    {
      "name":"ratio",
      "display":"拆分比例(0-100%)",
      "type":"number",
      "default":"75"
    }
  ],
  "merge-row":[],
  "merge-col":[
    {
      "name":"how",
      "display":"合并方式",
      "type":"list",
      "default":"inner",
      "list":[
        "inner",
        "left",
        "right",
        "outer"
      ]
    }
  ]
}